name: Lint

on:
  pull_request:
  merge_group:
  workflow_dispatch:

permissions:
  checks: write
  contents: read

jobs:
  run-linters:
    name: Check Format and Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install clang-tidy and clang-format
        uses: tecolicom/actions-use-apt-tools@v1
        with:
          tools: 'clang-format clang-tidy'

      - name: Set up CMake and Ninja
        uses: lukka/get-cmake@latest
        with:
          cmakeVersion: latest
          ninjaVersion: latest

      - name: Run Clang-Format
        run: |
          echo "Running clang-format..."
          echo "clang-format detected: $(which clang-format)"
          echo "---------------------------------------------------"
          ./automated/clang-format.sh
        shell: bash

      - name: Run Clang-Tidy
        run: |
          echo "Running clang-tidy..."
          echo "clang-tidy detected: $(which clang-tidy)"
          echo "run-clang-tidy detected: $(which run-clang-tidy)"
          echo "---------------------------------------------------"
          ./automated/clang-tidy.sh
        shell: bash
